import type { GetServerSideProps, NextPage } from 'next'
import Head from 'next/head'
import Header from '../components/Header'
import styles from '../styles/Home.module.css'
import {sanityClient, urlFor} from '../sanity'
import { Post } from '../typings'
import Link from 'next/link'

interface Props {
posts : Post
}

const Home: NextPage = ({posts}: Props) => {
console.log("🚀 ~ file: index.tsx ~ line 13 ~ posts", posts)
  
  return (
    <div className='max-w-7xl mx-auto'>
      <Head>
        <title>medium blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

   <Header />
   <div className='flex justify-between items-center bg-green-500 border-y border-black py-10 lg:py-0'>
      <div className='px-10 space-y-5'>
          <h1 className='text-6xl max-w-xl font-serif'>
            <span className='underline decoration-black decoration-4 cursor-pointer'>Medium</span> is a place to write, read, and connect
          </h1>
          <h2>
             It´s easy peasy Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quaerat labore perspiciatis amet ipsa sequi aliquid vel unde dolore ipsam facere harum cupiditate, at, minima odit illo ratione repudiandae nobis. Molestias?
          </h2>
      </div>
      <div>
        <h1 className='hidden md:inline-flex h-32 lg:h-full text-9xl font-serif'>M</h1>
      </div>
   </div>
   <div className='grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-3 md:gap-6 p-2 md:p-6'>
     {posts.map((post) =>  (
         <Link key={post._id} href={`/post/${post.slug.current}`}>
           <div className='border rounded-lg group cursor-pointer overflow-hidden'>
             <img className='h-60 w-full object-cover group-hover:scale-105 transition-transform duration-200 ease-in-out' src={urlFor(post?.mainImage).url()} alt="main" />
             <div className='flex justify-between p-5 bg-white'>
                <div>
                  <p className='text-lg font-bold'>{post.title}</p>
                  <p className='text-xs'>{post.description} by {post.author.name}</p>
                </div>
                <img className='h-12 w-12 rounded-full' src={urlFor(post.author.image).url()} alt="author" />
             </div>
           </div>
         </Link>
       )
     )}
   </div>
    </div>

// figure className='hero-container'>
//       <h1 className='blog-title'>{post?.title} </h1>
//   {post?.mainImage && <img className='blog-hero' alt='Some alt Text' src={urlForImage(post?.mainImage).url()} />}
//   </figure>

  )
}

export default Home


export const getServerSideProps = async() => {
  const query = `*[_type == "post"]{
    _id,
    title,
    author -> {
    name,
    image
  },
    description,
    mainImage,
    slug,
  }`;

  const posts = await sanityClient.fetch(query)
  return{
    props: {
      posts
    }
  }
}